version: "3.8"

x-build:
  &default-build
  context: .
  dockerfile: Dockerfile

services:
  app:
    container_name: marcosleal-app
    build: *default-build
    environment:
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
    volumes:
      - .:/app
    command: ["./scripts/start.sh",]

  lint:
    container_name: marcosleal-lint
    build: *default-build
    working_dir: /app
    volumes:
      - .:/app
    command: ["./scripts/start-lint.sh"]
